# roles/mariadb/defaults/main.yml
---

mariadb_databases:
  - name: '{{ mariadb_db_name }}'
mariadb_users: 
  - name: '{{ mariadb_user }}'
    password: '{{ mariadb_user_pass }}'
    priv: '*.*:ALL,GRANT'
    host: '%'

mariadb_root_password: ''
mariadb_auth_unix_plugin: false

mariadb_mirror: yum.mariadb.org
mariadb_version: '10.4'

mariadb_configure_swappiness: true
mariadb_swappiness: "0"

# 27 is default in /usr/share/doc/setup-*/uidgid
mariadb_system_user:
  name: 'mysql'
  uid: 27
  gid: 27
  shell: '/sbin/nologin'
  home: '/var/lib/mysql'
  comment: 'MySQL Server'

mariadb_logrotate:
  configure: true
  rotate: 3

# Network configuration (network.cnf)

mariadb_service: mariadb
mariadb_bind_address: '{{ mariadb_bind_address }}'

# Server configuration
mariadb_server_cnf: {}

# Custom configuration
mariadb_custom_cnf: {}
