---
# tasks file for firewall
- name: Disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Disable Selinux
  selinux:
    state: disabled
  ignore_errors: yes

- name: Disable Selinux without reboot
  shell: setenforce 0
  ignore_errors: yes
